### ISSUE TITLE
Articles TODO

### ISSUE THREAD

**Issue by nrgill28** [H3VR-Modding/wiki#7]
- Scripting
  - [x] Getting Started
  - [x] dnSpy
  - [ ] Interacting with the player
  - [ ] Creating Custom MonoBehaviours
  - [ ] Accessing Player Input
  - [ ]
